# See circleguard-gateway-service/values-stage.yaml for registry alignment notes.
image:
  repository: docker-registry:5000/circleguard-form-service
  tag: "stage"
  pullPolicy: Always

service:
  port: 8086

env: stage
replicaCount: 1
