apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    env: {{ .Values.env }}
    version: {{ .Values.image.tag }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env | quote }}
